### ISSUE TITLE
Can not get example code to work

### ISSUE THREAD

**Issue by shane-powell** [pimoroni/drv8830-python#1]
I am getting the following error when trying to run the sample code on my PI. I have two of these modules in my garden and tried the one without the cut trace in its own but still getting the same issue.

Traceback (most recent call last):
  File "motor-test.py", line 9, in <module>
    left.forward()
  File "/usr/local/lib/python2.7/dist-packages/drv8830/__init__.py", line 76, in forward
    self.set_direction('forward')
  File "/usr/local/lib/python2.7/dist-packages/drv8830/__init__.py", line 91, in set_direction
    self._drv8830.set('CONTROL', direction=direction)
  File "build/bdist.linux-armv6l/egg/i2cdevice/__init__.py", line 247, in __getattribute__
AttributeError: 'Device' object has no attribute 'set'

**Comment by shane-powell** [comment]
I managed to resolve this by building from a new buster lite image. However it still seems the example does not work as is. It looks to me like you need to call the set_voltage function for each motor to get anything to happen. By setting the voltage the motors now turn.

**Comment by shane-powell** [comment]
I have added a pull request with an update to the example that now works for me.

**Comment by Gadgetoid** [comment]
Thank you! I seem to have forgotten to close this now the PR is merged!
